//BUY CART
###
POST http://localhost:3000/order/buy
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzg3MTBlZTA3NDc1NjY3YWMzNzZmOTciLCJpYXQiOjE2Njk3OTYwOTAsImV4cCI6MTY2OTgwMzI5MH0.LbhzYyw8_JeGODuqdvJuQ4hpZ5YYVk078vXbLTlXAWc


//GET ORDERS BY USER
###
GET http://localhost:3000/order/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzg3MTBlZTA3NDc1NjY3YWMzNzZmOTciLCJpYXQiOjE2Njk3OTYwOTAsImV4cCI6MTY2OTgwMzI5MH0.LbhzYyw8_JeGODuqdvJuQ4hpZ5YYVk078vXbLTlXAWc