//CREATE A REVIEW
###
POST http://localhost:3000/review/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzg2ZGI5YmY1MjEwN2IyMDRiOWU3OGIiLCJpYXQiOjE2Njk3ODcxNDUsImV4cCI6MTY2OTc5NDM0NX0.ZwGJbDWlySo1ri7T5R08-AIgykEbV36YZQsF4_SZdSo

{
    "idProduct":"6386dfebe4a0095e97225d84",
    "description": "borralo",
    "calification": 4
}

//GET REVIEWS BY USER
###
GET http://localhost:3000/review/user/flcaro
Content-Type: application/json


//GET REVIEWS BY PRODUCTS
###
GET http://localhost:3000/review/product/6386dfebe4a0095e97225d84
Content-Type: application/json


//GET REVIEWS BY CALIFICATION
###
GET http://localhost:3000/review/calification
Content-Type: application/json

{
    "calification":2
}

//GET REVIEWS BY CALIFICATION
###
DELETE  http://localhost:3000/review/delete/6386af7b5595822d0c5d9fa1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzg2ODlmMjk3YjY5OTVkN2JlYjdjN2EiLCJpYXQiOjE2Njk3NzQxNDAsImV4cCI6MTY2OTc4MTM0MH0.nul0P1HtxhYzqzn_tQPkO0cPUDCcRNFCXLjpafNHqhw

//GET ADDITIONAL: REVIEWS BY USERNAME AND CALIFICATION 
###
GET http://localhost:3000/review/ru/freddy/4
Content-Type: application/json

//GET ADDITIONAL: REVIEWS BY ID PRODUCT AND CALIFICATION 
###
GET http://localhost:3000/review/rp/6386dfebe4a0095e97225d84/4
Content-Type: application/json