//GET ALL USERS
###
GET http://localhost:3000/user/


//CREATE USER
###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username":"flcaro1",
    "email":"flcaro1@gmail.com",
    "password":"admin"
}

//LOGIN WITH PASSWORD
###
POST http://localhost:3000/user/loginu
Content-Type: application/json

{
    "username":"flcaro",
    "password":"admin"
}

//LOGIN WITH ID
###
GET http://localhost:3000/user/logint/6386db9bf52107b204b9e78b
Content-Type: application/json

//DELETE USER
###
DELETE  http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzg2ODczNDk4YjJlYzFiYmUyMDc5MGEiLCJpYXQiOjE2Njk3NjMzMzYsImV4cCI6MTY2OTc3MDUzNn0.SAPuwiEBlbzRrqYVKEqbxLieX9JYxAIADIICn3DWl2U
Content-Type: application/json


//UPDATE USER
###
PUT  http://localhost:3000/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzg2ODczNDk4YjJlYzFiYmUyMDc5MGEiLCJpYXQiOjE2Njk3NjMzMzYsImV4cCI6MTY2OTc3MDUzNn0.SAPuwiEBlbzRrqYVKEqbxLieX9JYxAIADIICn3DWl2U

{
    "username":"probando",
    "email":"probando@gmail.com",
    "password":"probando"
}




