//GET ALL USERS
###
GET http://localhost:3000/user/


//CREATE USER
###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username":"freddy",
    "email":"freddy@gmail.com",
    "password":"freddy123"
}

//LOGIN WITH PASSWORD
###
POST http://localhost:3000/user/loginu
Content-Type: application/json

{
    "username":"admin",
    "password":"admin123"
}

//LOGIN WITH ID
###
GET http://localhost:3000/user/logint/6386db77f8edc3912c19f836
Content-Type: application/json

//DELETE USER
###
DELETE  http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzg2ODczNDk4YjJlYzFiYmUyMDc5MGEiLCJpYXQiOjE2Njk3NjMzMzYsImV4cCI6MTY2OTc3MDUzNn0.SAPuwiEBlbzRrqYVKEqbxLieX9JYxAIADIICn3DWl2U
Content-Type: application/json


//UPDATE USER
###
PUT  http://localhost:3000/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzg2ODczNDk4YjJlYzFiYmUyMDc5MGEiLCJpYXQiOjE2Njk3NjMzMzYsImV4cCI6MTY2OTc3MDUzNn0.SAPuwiEBlbzRrqYVKEqbxLieX9JYxAIADIICn3DWl2U

{
    "username":"probando",
    "email":"probando@gmail.com",
    "password":"probando"
}




